<?php

/**
 * PluginGMapSlotTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginGMapSlotTable extends aSlotTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginGMapSlotTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginGMapSlot');
    }
}